# Generated by Django 3.2.4 on 2022-10-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='username',
        ),
    ]
